name: Greet Contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Greet contributor
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;
            const message = `👋 Hi @${prAuthor}, thanks for opening this pull request! We appreciate your contribution. 🚀`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });
